#!/usr/bin/env bash
#
# Generate the short-name twin of every loop command.
#
# A plugin command's name comes from its filename; a frontmatter `name:` REPLACES that name
# rather than adding to it. 1.10.0 used `name:` for the short forms, so `/relay:test` stopped
# being listed in the `/` menu — it still ran when typed in full, but you could no longer find
# or autocomplete it. Two names means two files.
#
# Both other routes were tried and don't work:
#   - a symlink beside the source        → the loader ignores it ("Unknown command")
#   - a stub that injects the real body  → registers, then produces nothing (same class of
#     failure as the forwarding stub dropped in 1.10.0)
#
# So each twin is a real command file with the same body, generated from its source so the two
# can't drift. Edit the SOURCE (commands/test.md); never the twin (commands/rlt.md).
#
# Usage:  ./scripts/gen-short-names.sh          write the twins
#         ./scripts/gen-short-names.sh --check  fail if any twin is stale (pre-push + CI)
#
set -euo pipefail
cd "$(dirname "$0")/.."

cmds="plugins/relay/commands"

# short | source | the twin's one-line description (kept short: it is in every session's
#                 skill listing, where the source's full description already sits)
pairs=(
  "rle|explore|Short name for /relay:explore — turn a rough idea into a shaped brief on the board."
  "rlrf|refine|Short name for /relay:refine — ground a shaped brief against this project, into session-sized slices."
  "rln|next|Short name for /relay:next — a ranked shortlist from the board, then start the pick in a worktree."
  "rlc|continue|Short name for /relay:continue — resume an in-flight thread from its handover."
  "rlt|test|Short name for /relay:test — the verify step between build and ship: a PR and a structured test plan."
  "rls|ship|Short name for /relay:ship — the end-of-session loop: test → PR → review → fix → merge → handover."
  "rlrv|review|Short name for /relay:review — domain specialists review a PR or the current branch, merged into one report."
  "rlf|fix|Short name for /relay:fix — re-verify the latest review's findings against the code, fix them, tick them off."
  "rlh|handover|Short name for /relay:handover — write the cold-start handover for the next phase and commit it to main."
  "rlp|persist|Short name for /relay:persist — harvest a lap's lessons into guardrails, memory and release notes."
)

check=0
[ "${1:-}" = "--check" ] && check=1

# Emit the twin for one pair on stdout.
render() { # <short> <source> <description>
  local short="$1" src="$2" desc="$3" file="$cmds/$2.md"

  # Frontmatter, minus the two fields the twin supplies itself. `name:` must not survive:
  # it would rename the twin back onto the source's name and one of the two would lose.
  local fm
  fm="$(awk 'NR==1 && /^---$/ {inside=1; next} inside && /^---$/ {exit} inside' "$file" \
        | grep -vE '^(name|description):')"

  printf '%s\n' '---'
  printf '# GENERATED by scripts/gen-short-names.sh — do not edit.\n'
  printf '# Source: commands/%s.md · edit that file, then re-run the script.\n' "$src"
  # `name:` here is what registers the BARE form. The filename alone gives `/relay:rlt`;
  # only an explicit name gives `/rlt` with no prefix. On the twin it renames nothing —
  # it already matches the filename — so the source keeps its own full name.
  printf 'name: %s\n' "$short"
  printf 'description: %s\n' "$desc"
  [ -n "$fm" ] && printf '%s\n' "$fm"
  printf '%s\n' '---'

  # Body: everything after the closing --- of the frontmatter, verbatim.
  awk 'NR==1 && /^---$/ {inside=1; next} inside && /^---$/ {inside=0; body=1; next} body' "$file"
}

fail=0

# Guard: a `name:` on a source command silently un-lists it from the `/` menu again.
for pair in "${pairs[@]}"; do
  IFS='|' read -r short src _ <<<"$pair"
  if grep -qE '^name:' "$cmds/$src.md"; then
    printf '  ✗ %-46s %s\n' "$cmds/$src.md" "has a 'name:' field — remove it; the twin carries the short name"
    fail=1
  fi
done
[ "$fail" -ne 0 ] && { echo; echo "✗ short names belong in a twin file, not in the source's frontmatter."; exit 1; }

for pair in "${pairs[@]}"; do
  IFS='|' read -r short src desc <<<"$pair"
  twin="$cmds/$short.md"

  if [ "$check" -eq 1 ]; then
    if [ ! -f "$twin" ] || ! render "$short" "$src" "$desc" | diff -q - "$twin" >/dev/null 2>&1; then
      printf '  ✗ %-46s %s\n' "$twin" "stale or missing (source: $src.md)"
      fail=1
    else
      printf '  ✓ %-46s %s\n' "$twin" "in step with $src.md"
    fi
  else
    render "$short" "$src" "$desc" > "$twin"
    printf '  ✓ %-46s %s\n' "$twin" "← $src.md"
  fi
done

echo
if [ "$fail" -ne 0 ]; then
  echo "✗ short-name twins have drifted — run ./scripts/gen-short-names.sh and commit the result."
  exit 1
fi
[ "$check" -eq 1 ] && echo "✓ every short-name twin matches its source" || echo "✓ ${#pairs[@]} twins written"
